# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  thymeleaf.cache: false
  main.show-banner: false
  
#dubbo配置
  dubbo:
    server: true
    consumer:
      check: false
    provider: 
      delay: -1
      timeout: 150000
      retries: 0  # 服务调用重试次数，服务发布者不给重试，让服务调用者自己重试   
    application:  #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
      name: qmd-common-service
      id: qmd-common-service
      owner: common-service
    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
      port: 20880
      name: dubbo
    registry:     #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://192.168.101.90:2181 # zookeeper注册中心的地址
  
  ## 数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      username: tomcat
      password: tomcat123
      url: jdbc:mysql://192.168.101.80:3306/common_center?useUnicode=true&characterEncoding=utf-8&useSSL=false
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      validation-query: select 'x'
  #redis配置
  redis:
    host: 192.168.101.80
    port: 6379
    password: 123456
    timeout: 3000
    jedis: 
      pool:
        # 连接池中的最大空闲连接，默认值也是8。
        max-idle: 10
        # 连接池中的最小空闲连接，默认值也是0。
        min-idle: 0
        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
        max-active: 20
        # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
        max-wait: 1000
     

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
    type-aliases-package: cn.qumiandan.*.dao  # 注意：对应实体类的路径
    mapper-locations: classpath:cn/qumiandan/*/mapper/*.xml   #注意：一定要对应mapper映射xml文件的所在路径
    #type-handlers-package: com.example.typehandler
    configuration:
        map-underscore-to-camel-case: true
        default-fetch-size: 100
        default-statement-timeout: 30
        
mybatis-plus:
  global-config:
    db-config:
      id-type: auto 
      
# Logger Config
logging:
  config: classpath:logback-prod.xml

# 短信限制次数
ali:
 sms:
  smsLimitCountTime: 60 # 多少秒内限制 暂时没用到
  smsLimitCountNum: 5  # 多少秒内限制次数
  smsTimeout: 3600 # 秒 有效时间

verifyCode:
  periodOfValidity: 3600 #10分钟
 
  



#pagehelper
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql
#    returnPageInfo: check
